language: node_js
node_js:
- '4'
- '5'
- '6'
addons: 
after_success:
- npm run coverage
after_script:
- cat coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
- cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
